CREAR_FONDO = "CREAR_FONDO"
ACTUALIZAR_FONDO = "ACTUALIZAR_FONDO"
ELIMINAR_FONDO = "ELIMINAR_FONDO"

CREAR_USUARIO = "CREAR_USUARIO"
ACTUALIZAR_USUARIO = "ACTUALIZAR_USUARIO"
ELIMINAR_USUARIO = "ELIMINAR_USUARIO"
CAMBIO_CONTRASENA = "CAMBIO_CONTRASENA"

CREAR_ASOCIADO = "CREAR_ASOCIADO"
ACTUALIZAR_ASOCIADO = "ACTUALIZAR_ASOCIADO"
ELIMINAR_ASOCIADO = "ELIMINAR_ASOCIADO"
CARGA_MASIVA_EXITOSA = "CARGA_MASIVA_EXITOSA"

CREAR_MICROCUPO = "CREAR_MICROCUPO"
MICROCUPO_APROBADO = "MICROCUPO_APROBADO"
MICROCUPO_DENEGADO = "MICROCUPO_DENEGADO"
MICROCUPO_ACTUALIZADO = "MICROCUPO_ACTUALIZADO"

RECARGAR_CUPO = "RECARGAR_CUPO"
ASIGNAR_CUPO = "ASIGNAR_CUPO"

VENTA_REALIZADA = "VENTA_REALIZADA"

CREAR_PUNTO_VENTA = "CREAR_PUNTO_VENTA"

FONDO_EJECUTIVO_ASIGNADO = "FONDO_EJECUTIVO_ASIGNADO"

CREAR_ENTREGA = "CREAR_ENTREGA"

CREAR_IP_WHITELIST = "CREAR_IP_WHITELIST"
ACTUALIZAR_IP_WHITELIST = "ACTUALIZAR_IP_WHITELIST"
ELIMINAR_IP_WHITELIST = "ELIMINAR_IP_WHITELIST"

LOGIN_EXITOSO = "LOGIN_EXITOSO"

REPORTE_EXPORTADO = "REPORTE_EXPORTADO"

CARTERA_RECARGA = "CARTERA_RECARGA"
CARTERA_ABONO = "CARTERA_ABONO"
